### ISSUE TITLE
Grid Issues

### ISSUE THREAD

**Issue by mato0039** [mato0039/more-than-just-datum#1]
Hi Christina

I am having issues matching the screenshots and the medium and large screen sizes. The table stays at the bottom of the page on both sizes then in the extra large screen it follows the grid.

Is this because of the min-width I put on the table?

I'm really confused. 

@muxlowc

<img width="671" alt="Screen Shot 2020-03-24 at 11 15 04 AM" src="https://user-images.githubusercontent.com/55108737/77442505-d604ab00-6dc0-11ea-8082-9444f57c00a3.png">

<img width="1004" alt="Screen Shot 2020-03-24 at 11 15 15 AM" src="https://user-images.githubusercontent.com/55108737/77442532-db61f580-6dc0-11ea-9219-9a16fa32fd5d.png">

**Comment by mato0039** [comment]
Also, how do I add the magnifying glass image in the input bar? 

@muxlowc

**Comment by muxlowc** [comment]
Hey @mato0039 

1) first of all, you only need to have a form for the search bar - nothing else should be in the form because it's separate. Also, see below how to get the magnifying glass in there:

```
      <form class="relative" action="#">
        <label class="search-icon icon i-18 pin-lc" for="find" title="Search"><img src="images/search.svg" alt="Find"></label>
        <input class="search-input" type="search" id="find" required>
      </form>
```

3) So what you need to do is put your ul/li s into one grid/one unit, rather than individual ones. I started it here for you:

```
<div class="grid grid-stretch">
    <div class="panel-near unit xs-1 s-1 m-1-3 l-1-4 island-1-2">
      <h2 class="giga push-1-2">Nearest playgrounds</h2>

      <ul class="near-list list-group push-0">
        <li class="card island-1-2 push-1-2">
          <h3 class="mega push-0">373</h3>
          <dl class="list-group-inline push-0">
            <dt class="push-0 italic milli">Distance</dt>
            <dd class="push-0">0.75 km</dd>
          </dl>
        </li>
....
```

and then you'll have another unit for your Playgrounds in the City:

```
....
<div class="panel-data unit xs-1 s-1 m-2-3 l-3-4 island-1-2">
      <div class="table-wrapper scrollable">
        <table class="push-0">
          <caption class="bold not-italic giga push-1-2">Playgrounds in the city</caption>
          <thead>
```

(some of these classes can be named differently etc, but just so you get the jist! Hope this helps!)

**Comment by mato0039** [comment]
Thanks a lot Christina!

I've managed to fix it I think! I'm still a few percentages away from making Markbot happy. 

Do you know what this means? 

<img width="505" alt="Screen Shot 2020-03-24 at 12 21 17 PM" src="https://user-images.githubusercontent.com/55108737/77450672-00a73180-6dca-11ea-9d2f-624f32f47776.png">

I really appreciate your help! 

Cathy

**Comment by mato0039** [comment]
It worked! 

Thanks a lot :)

Cathy
